### ISSUE TITLE
Meson requires to set the root include dir by setting the INCLUDE env var

### ISSUE THREAD

**Issue by nacho** [wingtk/gtk-win32#124]
@gurudanny67 we should probably fix this problem otherwise the header files that are in the root dir will not be found.

**Comment by TingPing** [comment]
I haven't tried it personally, but maybe `LIB` and `LIBPATH` too?

**Comment by guruDanny67** [comment]
Which projects can I use to test this ?

Thanks

**Comment by TingPing** [comment]
To test include:

```meson
project('foo', 'c')

cc = meson.get_compiler('c')
cc.has_header('libintl.h')
```

**Comment by guruDanny67** [comment]
Ok, you mean the gtk stack include dir (i.e. c:\gtk-build\gtk\win32\release\include) and the similar for libpath ?

**Comment by TingPing** [comment]
Yea.

**Comment by guruDanny67** [comment]
If I understand correctly (I'm at work now and I can't check deep) if the project use ONLY pkg-config to get the stuff it's ok (because LIBPATH and the include dir are added), while in these simple case we got an error.

We can add the enviroment globally in the script (or before, manually, to test things) or on a per-project basis, like the add_path keyword

**Comment by TingPing** [comment]
> if the project use ONLY pkg-config to get the stuff it's ok (because LIBPATH and the include dir are added), while in these simple case we got an error.

Indeed.

I think it is safe to always set these variables and would avoid potential duplication.

**Comment by guruDanny67** [comment]
A fast solution will be to set (or add) INCLUDE, LIB and LIBPATH to the gtk ones just before initializing the vs environment (vcvarsall.bat): in this way the data are saved internally and any time we use the build_vs(...) we have it.
