### ISSUE TITLE
Add adwaita-icon-theme

### ISSUE THREAD

**Issue by nacho** [wingtk/gtk-win32#6]
In order to build it we need to first have libcroco, librsvg, hicolor-icon-theme and icon-naming-utils. @fanc999 have you had any luck on building this and creating the proper projects etc?

**Comment by nzjrs** [comment]
I usually just follow the instructions which @fanc999 has on l.g.o and only ship png icons. We could fake building it by converting the svg to png via msys2/imagemagik and programatically generate the icon theme index file

**Comment by nacho** [comment]
we could also just get it from msys2 directly using pacman, the point is. It sucks that we depend on something else to get that generated :)

**Comment by nacho** [comment]
Also there is the point that the spinner depends on an svg resource, and without librsvg we will not get that working afaik

**Comment by nzjrs** [comment]
true about the spinner. I didn't notice that.

**Comment by fanc999** [comment]
Hi Nacho,

For the icons, this is what I did:

Libcroco already has the MSVC projects upstream, which would depend on libxml2, which has nmake makefiles shipped that is used to build with MSVC.  I will need to look into librsvg for getting MSVC build support in there, in which the code should be buildable by MSVC at this time.

The thing is, since we want the icons to be relocatable, we need to use hicolor-icon-theme (which is a very small package), and place index.theme from that package into $(gtk_root_dir)\share\icons, and copy all the icon files in their respective directories in gnome/ (or so) from the adwaita-icon-theme package as-is to where we just copied index.theme.  Essentially we don't do a build on adwaita-icon-theme, as trying to build that through the normal way will cause paths to be hardcoded.

This copy of the files would probably need to be done as a .bat or nmake Makefile, if we want to automate that.

P.s. I am aware that Alex has a tool in gtk+ to convert the .svg's to .png's, but running that tool would mean librsvg (as we need svg's support in gdk-pix if) if is needed (though this would free the end user from depending on libxml2, libcroco and librsvg).

A few my thoughts regarding this, with blessings.

**Comment by codekiddy2** [comment]
Hello guys, are you still having problems building icons? I managed to build them (Adwaita) by using MSYS2, here is what I did, hopefully you find this information useful.

Usually there was a problem spamming the console about converting svg format to png, I'm not even sure what my MSYS2 installation had installed in that time but here is for what I'm sure I installed:
(note, this indirectly installs librsvg, libxml2 and libcroco, I think so, if not install extra )

`pacman -S pkg-config`
`pacman -S make autoconf autogen automake icon-naming-utils intltool itstool`

I ensured PKG_CONFIG_PATH and pkg-config to point to MSYS2 *.pc files and that *.pc files are in place and correct.

then standard `configure && make && make install` against the source package built all the icons with no errors and installed them into share/icons/adwaita.

I also ended up with index-theme file.

afterwards I used following before compiling GTK+(mm):

`gtk-update-icon-cache --update-cache`

and

`gtk-update-icon-cache -v`

there were no errors and my gtk(mm) built applications do not miss any icons.
Performed the same procedure for hicolor icon theme as well.

BTW, it is possible to "integrate" MSYS2 into Visual Studio, so that entry build process is done in Visual Studio. therefore the end user is not required to perform headache preparation of MSYS2 or use MSYS2 before building icons.

The same could be applied to powershell script, of course.

**Comment by pbor** [comment]
Yes, this is definitely still an open issue, we need to come up with a good automated way.

Thanks for your input

**Comment by pbor** [comment]
I added libcroco, librsvg and hicolor-icon-theme to the script and they all build fine.

hicolor-icon-theme only installs the index file and not real icons... it is not clear to me if it is useful at all or if real themes will overwrite that file anyway.

Now the real work is to figure out adwaita-icon-theme

**Comment by codekiddy2** [comment]
hicolor does not build icons.

Adwaita, hicolor as well as other icon themes can be installed side by side AFIAK.
what matters it the index.theme file. and to run gtk-update-icon-cache on each of them, that is for each icon theme package.

I've used following flags (although redundant some of them), I've copied this from 
[link](https://github.com/codekiddy2/Visual-Studio-gtkmm/blob/master/projects/adwaita-icon-theme-3.18.0/msvc-140/adwaita-icon-theme/adwaita-icon-theme.sh)
This are environment flags preset, just replace them with your build type. and run from MSYS2 with stuff installed from my previous post and it should work.

```
	$SRC_DIR/configure \
	CC=cl \
	CXX=cl \
	CPP='cl -EP' \
	CXXCPP='cl -E' \
	AR=lib \
	LD=link \
	CFLAGS='' \
	CXXFLAGS='' \
	CPPFLAGS='' \
	LDFLAGS='' \
	LIBS='' \
	--build=x86_64-w64-mingw32 \
	--host=x86_64-w64-mingw32 \
	--target=x86_64-w64-mingw32 \
	--prefix=/d/out/
```

**Comment by pbor** [comment]
Sorry I was not clear, I know that hicolor does not have actual icons and that themes can live side by side.  What I would like to achieve is to install those themes without having the full migw stuff.

So I would expect to add the following steps to the script:

1) add the tarballs to the script (already done for hicolor, easy for adwaita)
2) for adwaita-icon-theme,  add code to generate index.theme
3) copy the hicolor and Adwaita folders in C:\gtk-build\gtk\share\icons
4) gtk-update-icon-cache on each theme

Now my problems are:

A) for step (2) there is no script that does the generation: workaround for now we can simply commit the index.theme generated on linux or with msys and worry about this later. Is this correct? Or does the index file need to be modified because it is different from the one on linux? I do not see paths or similar stuff in the file

B) I still do not understand if hicolor is needed since it does not have any actual icons... on linux applications install their icons in that dir and then the cache gets updated but does this actually matter on windows?

C) Fan's instructions on the wiki seems to imply that adwaita icons should be copied in hicolor... is this correct? if yes why? Does gtk try to use the adwaita theme by default or not?

D) gtk-update-icon-cache is not built in our projects (and also in upstream Fan's projects) as far as I can see... should it be added? or is it skipped on purpose?

E) In my steps did I miss something? Do we need to replace the symlink stuff that is done on linux? Do we need to do something special for cursors?


If any of you can answer to even some of these questions, it would be really appreciated :)

**Comment by codekiddy2** [comment]
Oh, I see now, I miss understood your problem, sorry for that. you want to build Adwaita solely by using PS and custom libs and not MSYS2 and it's provided libs?

A) I never tried that and I suspect this could involve to build a whole host of dependent packages in order to rework and apply the script from Adwaita source to PS.  ( too much overhead )
BTW, Why not make PS script call MSYS2 to do the job, the build process will be automated, and you can even automate the installation and system update of MSYS2 from PS.

B) I don't know, I think hicolor is useless, ie. I haven't seen any benefit of it in GTK on Windows. as you said, the path to hicolor will not be used by any app on Windows.

C) I built Adwaita only (index.theme and all the icons ) with MSYS2 without hicolor, the installation script installed Adwaita into *share/icons/Adwaita*, then I performed update-cache part and GTK used the theme and worked as expected. therefore obviously hicolors' empty folder structure makes no sense or purpose on Windows.

D) I think It should be added, it's purpose is to cache the icons and improve the icon load for GTK stack. a single source file to build the utility can be found in GTK+ source package.
which theme GTK+ uses by default is configurable by using the 
`#define DEFAULT_THEME_NAME`. 

to have GTK+ use "Adwaita" you define:
`#define DEFAULT_THEME_NAME "Adwaita"`. (which is default) and then compile GTK+

E) not sure, I'm not much into PS usage, but for the symlinks part I bet steps applied on linux do not apply to Windows.

**Comment by pbor** [comment]
For what is worth I went ahead and tried to just copy Adwaita into the share/icons using the index.theme generated on linux and things seems to work (gtk3-demo does not print criticals  anymore).

I think the next thing is to build gtk-update-icon-cache and call it.



With regard to (A) I would like to avoid requiring to install all the msys build tools, the adwaita-icon-theme makefile does not see to do much more than a few sustitutions so it should not bee too hard to replace. For now just committing the generated index.theme seems to work

**Comment by codekiddy2** [comment]
Note that gtk3-demo criticals depend not only on icons, but also on where the demo data gets installed.

I think there are other GTK+ utilities and tools not built by default, so you might be interested in building these too if not already.

full list:
gtk-query-immodules
gtk-update-icon-cache
gtk-encode-symbolic-svg
gtk-icon-browser

**Comment by pbor** [comment]
I pushed a wip/icons branch which adds and runs gtk-update-icon-cache however as far as I can see the cache file is not getting created 

I am even more confused now...

**Comment by pbor** [comment]
That was my fault, it is fixed on the branch now, on wip/icons everything should work as expected.

Unless anyone spots something wrong I think we can merge it.

What would be nice to fix upstream is:
 - the msvc project to build gtk-update-icon-cache
 - a small nmake file or bar script to be included in adwaita

**Comment by spk121** [comment]
Dunno if this is still an issue, but, over the weekend I built a GTK3 with your method and then tried to compile and build a sample application.  I built in Visual Studio and added all the include and lib paths manually added to the VS project. It compiled fine but wouldn't run because GTK aborts upon not being able to find any icons or themes.

I know that Adwaita is the common theme but was unable to guess how to create and install it in this context.

**Comment by nacho** [comment]
The crash in gtk3-demo should be fixed now so the next gtk release should have the fix.

**Comment by nacho** [comment]
See https://git.gnome.org/browse/gtk+/commit/?h=gtk-3-20&id=3d76005585f10337c68a0d0659b8de2138d77860

**Comment by nacho** [comment]
I pushed adwaita-icon-theme to the script. I am closing this now. If something we can open another issue to track other problems.
